### ISSUE TITLE
Error in node@10 and npm@6

### ISSUE THREAD

**Issue by dooboolab** [luizstacio/select-shell#10]
It is throwing error after `selectShell` when I try to input any keys such as `enter` or `arrow keys`.

I downgraded to node@8 & npm@5 in homebrew then it is working again.

I am using `select-shell@1.0.1`

**Comment by luizstacio** [comment]
@dooboolab is your first install or It stopped work after some update? Thanks

**Comment by diesal11** [comment]
I'm getting `Error: write EPIPE` on Node 10 as well when using arrow keys. This is my first time using the package.

Downgrading to Node 8 fixed the issue.

If i get some time over the next few days I can investigate & make a PR unless someone else gets to it first. :)

**Comment by luizstacio** [comment]
@diesal11 awesome I will give you some time to do this. I will be available only on next week! Thanks a lot!

**Comment by asbjornh** [comment]
I'm getting the same error in node `8.9.4` but only on Windows. On MacOS it works fine with the same version. Also using `select-shell@1.0.1`

**Comment by dooboolab** [comment]
<img width="959" alt="screen shot 2018-06-30 at 2 31 28 am" src="https://user-images.githubusercontent.com/27461460/42106093-b9ce21a6-7c0d-11e8-8afb-e9c64e10ca08.png">

Here is additional error log for more understanding.

**Comment by skaffolder** [comment]
This issue is related to readline package, on node >8 it is a new standard node package, but seem like it causes this error

**Comment by skaffolder** [comment]
Te reproduce the error on a new file you can write:
 readline.cursorTo(process.stdin, 0);
