### ISSUE TITLE
Return to select when using multiSelect: false

### ISSUE THREAD

**Issue by mulhoon** [luizstacio/select-shell#4]
Great little plugin Luiz!

One question - is it possible to just hit return on the desired choice when you only require one selection. To save users having to tap right/left ?

Thanks
Nic

**Comment by luizstacio** [comment]
Very interesting I will looking this. If you want to, you can create a PR, feel free. =) Thanks for the contribution.

**Comment by mulhoon** [comment]
Hi Luiz.

I submitted a pull request for this. As you might see, the pull request has a deleted commit for pushing an array of values to option, but I can submit that later. Would really love to include this in a node project of mine.

**Comment by luizstacio** [comment]
https://github.com/luizstacio/select-shell/pull/5
