### ISSUE TITLE
select callback doesn't return selected options

### ISSUE THREAD

**Issue by eric-wood** [luizstacio/select-shell#8]
When doing a single selection list, the callback function returns an empty array. It looks like `optionsSelected` under these circumstances never gets populated with the option the user selected.

# Steps to reproduce

I was able to reproduce this using the example (`sample.js`) provided in this repo.

# Result

Here's the output after choosing option `Two` and pressing enter:

```
❯ node sample.js
    ◎   One
 ▸  ◎   Two
    ◎   Three
select []
```

The results of `.on('select')` are always an empty array.

# Expected

I was hoping I'd get `"Two"` or the key value pair passed in for the option.

I do realize I could be using this wrong, but this seems like an unexpected result.

Thanks!

**Comment by luizstacio** [comment]
Hi thanks to open this issue, I will reproduce and fix A.S.A.P, but feel free to do a pull request! Thanks =)

**Comment by luizstacio** [comment]
@eric-wood I believe you are trying to use it in the wrong way. You should select them with the arrows before press "enter" to get the selected items.

look the instructions:
```
Up and Down - Navigates on the options
Right - Check the option
Left - Uncheck the option
Enter/Return - confirms the options selected
Esc - Cancel/Exit
```

Thanks for the issue.
